# Generated by Django 5.2 on 2026-03-31 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shared.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
