# Generated by Django 5.2 on 2026-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
