# Generated by Django 5.2 on 2026-04-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_document_certificate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Hujjat', 'verbose_name_plural': 'Hujjatlar'},
        ),
        migrations.AlterModelOptions(
            name='documentresult',
            options={'verbose_name': 'Hujjat natijasi', 'verbose_name_plural': 'Hujjat natijalari'},
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='shared.documenttype'),
        ),
    ]
