# Generated by Django 5.2 on 2026-04-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_documenttype_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('document', 'Document')], default='order', max_length=100),
        ),
        migrations.CreateModel(
            name='AiDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='ai_documents/')),
                ('total_words', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SI Detektor',
                'verbose_name_plural': 'SI Detektorlar',
            },
        ),
        migrations.CreateModel(
            name='AiDocumentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='shared.aidocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
