# Generated by Django 5.2 on 2026-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_alter_order_options_order_type_aidocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidocument',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
