# Generated by Django 5.2 on 2026-04-06 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_aidocument_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ai_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_orders', to='shared.aidocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SI Buyurtma',
                'verbose_name_plural': 'SI Buyurtmalar',
            },
        ),
    ]
