# Generated by Django 5.2 on 2026-04-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_aiorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiorder',
            name='ai_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_order', to='shared.aidocument'),
        ),
    ]
