# Generated by Django 5.2 on 2026-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_alter_aiorder_ai_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocument',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
