# Generated by Django 5.2 on 2026-04-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_alter_aidocument_total_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiorder',
            name='ai_document',
        ),
        migrations.RemoveField(
            model_name='aiorder',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='ai_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_order', to='shared.aidocument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shared.document'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('document', 'Document'), ('ai_document', 'AI Document')], default='order', max_length=100),
        ),
    ]
