# Generated by Django 5.2 on 2026-04-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_remove_aiorder_ai_document_remove_aiorder_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiOrder',
        ),
        migrations.AlterField(
            model_name='order',
            name='ai_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='shared.aidocument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='shared.document'),
        ),
    ]
