# Generated by Django 5.2 on 2026-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_delete_aiorder_alter_order_ai_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('document', 'Document'), ('ai_document', 'AI Document')], default='document', max_length=100),
        ),
    ]
