# Generated by Django 5.2 on 2026-04-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_alter_order_ai_document_alter_order_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ai_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shared.aidocument'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shared.document'),
        ),
    ]
