# Generated by Django 5.2 on 2026-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0020_seed_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="multicardtransaction",
            name="payment_system",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="multicardtransaction",
            name="payment_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
