# Generated by Django 5.2 on 2026-06-12 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0021_multicardtransaction_payment_system_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardRequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100, verbose_name="Davlat")),
                (
                    "country_code",
                    models.CharField(
                        help_text="Masalan: UZ, KZ, KG, TJ",
                        max_length=2,
                        verbose_name="Davlat kodi (ISO)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Masalan: UZS, KZT, KGS, TJS",
                        max_length=3,
                        verbose_name="Valyuta",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(max_length=30, verbose_name="Karta raqami"),
                ),
                (
                    "card_holder",
                    models.CharField(max_length=200, verbose_name="Karta egasi"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Bank"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=15,
                        verbose_name="Kurs (1 UZS → mahalliy valyuta)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Karta rekviziti",
                "verbose_name_plural": "Karta rekvizitlari",
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="Kod"),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        help_text="1–100 oralig'ida", verbose_name="Chegirma (%)"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Bo'sh bo'lsa muddatsiz",
                        null=True,
                        verbose_name="Amal qilish muddati",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 — cheksiz",
                        verbose_name="Maksimal ishlatish",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ishlatilgan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Promo-kod",
                "verbose_name_plural": "Promo-kodlar",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="ai_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("multicard", "Multicard"),
                    ("balance", "Balans"),
                    ("payme", "Payme"),
                    ("card_transfer", "Karta o'tkazmasi"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CardTransferPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt",
                    models.FileField(
                        upload_to="card_receipts/", verbose_name="Chek (rasm/PDF)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(default="UZS", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Tasdiq kutilmoqda"),
                            ("approved", "Tasdiqlandi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_transfers",
                        to="shared.order",
                    ),
                ),
                (
                    "requisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="shared.cardrequisite",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_card_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Karta o'tkazmasi (chek)",
                "verbose_name_plural": "Karta o'tkazmalari (cheklar)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_usage",
                        to="shared.order",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="shared.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo ishlatilishi",
                "verbose_name_plural": "Promo ishlatilishlari",
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("1h", "1 soatdan keyin"),
                            ("24h", "24 soatdan keyin"),
                        ],
                        max_length=4,
                    ),
                ),
                ("channel", models.CharField(default="telegram", max_length=20)),
                ("delivered", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="shared.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov eslatmasi",
                "verbose_name_plural": "To'lov eslatmalari",
                "unique_together": {("order", "kind")},
            },
        ),
    ]
