# Generated by Django 5.2 on 2026-04-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
