FROM python:3.12-bullseye

WORKDIR /code

# PostgreSQL 17 client + boshqa paketlar
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y \
    gdal-bin \
    libgdal-dev \
    python3-gdal \
    libgeos-dev \
    libproj-dev \
    g++ \
    make \
    wget \
    libfontconfig \
    libxrender1 \
    libjpeg-dev \
    xfonts-base \
    postgresql-client-17 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./ /code
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install -r requirements.txt

CMD ["sh", "./resources/scripts/entrypoint.sh"]
